#!/usr/bin/env bash

##
## This script boots up bosh-lite in a local Vagrant/Virtualbox VM,
## then uploads and deploys Cloud Foundry into it.
## Finally, it logs into Cloud Foundry as an admin user,
## creates an initial organization and space,
## then deploys an example application.
##

set +x

##
## Dependency locations
##
BOSH_LITE_REPO=${BOSH_LITE_REPO:-https://github.com/cloudfoundry/bosh-lite.git}
CF_RELEASE_VERSION=${CF_RELEASE_VERSION:-164}
CF_RELEASE_TGZ_URL=${CF_RELEASE_TGZ:-https://github.com/cloudfoundry/cf-release/archive/v$CF_RELEASE_VERSION.tar.gz}
STEMCELL_NAME=${STEMCELL_NAME:-bosh-stemcell-24-warden-boshlite-ubuntu.tgz}

GEMFIRE_BOSH_RELEASE_REPO=${GEMFIRE_BOSH_RELEASE_REPO:-https://github.com/jcherng-pivotal/gemfire-bosh-release.git}

APPLICATION_URL=${APPLICATION_URL:-https://github.com/cloudfoundry-community/cf-env.git}
APPLICATION_NAME=${APPLICATION_NAME:-cf-env}

WORKSPACE_DIR=${WORKSPACE_DIR:-$HOME/bosh-lite-tutorial}
CF_PROJECT_NAME=cf-release
CF_RELEASE_NAME=cf
CF_RELEASE_DIR=$WORKSPACE_DIR/$CF_PROJECT_NAME-$CF_RELEASE_VERSION
CF_SOURCE_RELEASE_TGZ=$WORKSPACE_DIR/$CF_PROJECT_NAME-v$CF_RELEASE_VERSION.tar.gz
CF_FINAL_RELEASE_TGZ=$RELEASE_DIR/releases/$CF_RELEASE_NAME-$CF_RELEASE_VERSION.tgz

GEMFIRE_PROJECT_NAME=gemfire-bosh-release
GEMFIRE_RELEASE_NAME=cf-gemfire
GEMFIRE_RELEASE_DIR=$WORKSPACE_DIR/$GEMFIRE_PROJECT_NAME-$GEMFIRE_RELEASE_VERSION
GEMFIRE_SOURCE_RELEASE_TGZ=$WORKSPACE_DIR/$GEMFIRE_PROJECT_NAME-v$GEMFIRE_RELEASE_VERSION.tar.gz
GEMFIRE_FINAL_RELEASE_TGZ=$RELEASE_DIR/releases/$GEMFIRE_RELEASE_NAME-$GEMFIRE_RELEASE_VERSION.tgz

##
## Verify local requirements
##
if [[ "${SKIP_VERIFY}X" == "X" ]]; then
    set +e

    echo Required dependencies: ruby 1.9.3, vagrant 1.4+, git 1.7+, wget, spiff 0.3+, gcf 6.0+
    echo

    ruby_installed=$(which ruby)
    ruby -v

    echo
    vagrant_installed=$(which vagrant)
    vagrant -v

    echo
    git_installed=$(which git)
    git --version

    echo
    wget_installed=$(which wget)
    wget --version | head -n1

    echo
    spiff_installed=$(which spiff)
    spiff --version

    echo
    cf_installed=$(which cf)
    cf --version

    echo
    if [[ "${ruby_installed}X" == "X" || "${vagrant_installed}X" == "X" || "${git_installed}X" == "X" || "${wget_installed}" == "X" || "${spiff_installed}X" == "X" || "${cf_installed}X" == "X" ]]; then
        echo Please install the missing dependencies above.
        echo
        if [[ "${ruby_installed}X" == "X" ]]; then
            echo ruby    - http://rvm.io
        fi
        if [[ "${vagrant_installed}X" == "X" ]]; then
            echo vagrant - http://www.vagrantup.com/downloads.html
        fi
        if [[ "${spiff_installed}X" == "X" ]]; then
            echo spiff   - https://github.com/cloudfoundry-incubator/spiff/releases
        fi
        if [[ "${cf_installed}X" == "X" ]]; then
            echo cf     - https://github.com/cloudfoundry/cli#installers
        fi
        exit 1
    fi
    echo Press [ENTER] if your versions are ok, else Ctrl-C to cancel and manually install them.
    read

    ##
    ## Workspace setup
    ##

    echo Will use $WORKSPACE_DIR for this demo. Press [ENTER] or re-run with \$WORKSPACE_DIR set.
    read
fi

set -e # exit on error
set -x # show commands being run

mkdir -p $WORKSPACE_DIR
cd $WORKSPACE_DIR

cd $WORKSPACE_DIR
if [[ ! -f Gemfile ]]; then
    echo "source 'https://rubygems.org'; gem 'bosh_cli'" > Gemfile
    bundle install
fi
if [[ ! -f $CF_SOURCE_RELEASE_TGZ ]]; then
    wget $CF_RELEASE_TGZ_URL -O $CF_SOURCE_RELEASE_TGZ
fi
if [[ ! -d $CF_RELEASE_DIR ]]; then
    tar xfz $CF_SOURCE_RELEASE_TGZ
    cd $CF_RELEASE_DIR
    bundle install
fi
if [[ ! -f $CF_FINAL_RELEASE_TGZ ]]; then
    cd $CF_RELEASE_DIR
    rm -f Gemfile*
    bundle exec bosh create release --force --with-tarball releases/cf-$CF_RELEASE_VERSION.yml
fi
cd $WORKSPACE_DIR

if [[ ! -d bosh-lite ]]; then
    set -x
    git clone $BOSH_LITE_REPO bosh-lite
    cd bosh-lite
    rm -f Gemfile*
    set +x
fi

cd $WORKSPACE_DIR
if [[ ! -f $STEMCELL_NAME ]]; then
    bundle exec bosh download public stemcell $STEMCELL_NAME
fi

cd $WORKSPACE_DIR/bosh-lite

if [[ "${NO_REBUILD}X" == "X" ]]; then
    vagrant destroy -f
fi
vagrant up

set +e # do not exit on error; allow these to fail if already performed
yes admin | bosh target https://192.168.50.4:25555
bosh upload release $CF_FINAL_RELEASE_TGZ
bosh upload stemcell $WORKSPACE_DIR/$STEMCELL_NAME
set -e # exit on error

# specifically for cf-release/bosh-lite need to setup $CF_RELEASE_DIR
#export CF_RELEASE_DIR=${RELEASE_DIR}
scripts/make_manifest_spiff

##
## Deploy Cloud Foundry into our BOSH (bosh-lite)
## 
bosh -n deploy

bosh status
bosh vms

##
## Setup Cloud Foundry
##

cd $WORKSPACE_DIR/bosh-lite
./scripts/add-route # to access 10.244.0.34 via host machine

cf api --skip-ssl-validation https://api.10.244.0.34.xip.io
cf auth admin admin

cf create-org me
cf target -o me

cf create-space test
cf target -s test

##
## Deploy GemFire into our BOSH (bosh-lite)
##
cd $WORKSPACE_DIR

if [[ ! -d gemfire-bosh-release ]]; then
    git clone -b pivotal-gemfire-bosh-release $GEMFIRE_BOSH_RELEASE_REPO gemfire-bosh-release
fi
cp -r $WORKSPACE_DIR/blobs/ $WORKSPACE_DIR/gemfire-bosh-release/blobs/
cd $WORKSPACE_DIR/gemfire-bosh-release
bosh create release --force
bosh upload release
bosh deployment gemfire-bosh-lite.yml
bosh -n deploy

##
## Deploy example application
##

cd $WORKSPACE_DIR

if [[ ! -d $APPLICATION_NAME ]]; then
    git clone $APPLICATION_URL $APPLICATION_NAME
fi
cd $APPLICATION_NAME
bundle
cf push $APPLICATION_NAME

cf apps
