#!/usr/bin/env bash

set -e # exit on error
set -x # show commands being run

##
## Configure Cloud Foundry
##
echo configure Cloud Foundry ...
echo

cd $WORKSPACE_DIR/bosh-lite
./scripts/add-route # to access 10.244.0.34 via host machine

cf api --skip-ssl-validation https://api.10.244.0.34.xip.io
cf auth admin admin

cf create-org me
cf target -o me

cf create-space test
cf target -s test
