#!/usr/bin/env bash

set -e # exit on error
set -x # show commands being run

##
## Create GemFire service
##
echo creating GemFire service ...
echo

cf create-service pivotal-gemfire 1GB-replicated pivotal-gemfire-1
cf curl /v2/service_plans/$GUID -X 'GET'
