#!/usr/bin/env bash

set -e # exit on error
set -x # show commands being run

##
## Create GemFire service broker
##
echo create GemFire service broker ...
echo

cf create-service-broker gemfire admin admin http://10.244.0.102:8888
GUID=$(cf curl /v2/service_plans -X 'GET' | grep '"guid":' | sed 's/\"guid": //' | tr -d ' ",')
cf curl /v2/service_plans/$GUID -X 'PUT' -d '{"public":true}'
