#!/usr/bin/env bash

set -e # exit on error
set -x # show commands being run

##
## Deploy application with default buildpack and bind pivotal gemfire service
##
echo push application - $APP_NAME and bind with default buildpack ...
echo

cd $WORKSPACE_DIR

if [[ ! -d $APP_NAME ]]; then
    git clone $APP_REPO $APP_NAME
fi
cd $APP_NAME
bundle
cf push $APP_NAME --no-start
cf bind-service $APP_NAME $GF_SERVICE_NAME
cf push
